panda_arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.05
  # The kinematics_solver_search_resolution parameter allows you to control the granularity or step size used 
  # when searching this configuration space. By setting this parameter, you're essentially defining the level
  #  of precision or detail in the search process.