# Default initial positions for the panda arm's ros2_control fake system
initial_positions:
  panda_joint1: -0.1334
  panda_joint2: -0.2388
  panda_joint3: -0.6939
  panda_joint4: -2.3524
  panda_joint5: -0.1830
  panda_joint6: 2.1595
  panda_joint7: 0.0342
